"""
(C) David J. Kalbfleisch 2013

All rights reserved.  You are welcome to inspect this code for your education or to evaluate
the author's qualifications.  No other uses are permitted.
"""

# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'As you want it to appear to volunteers', max_length=100, verbose_name=b'Campaign name')),
                ('phone_number', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=False, help_text=b'(yes)', verbose_name=b'Accepting volunteers, reports about voters, etc.?')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_electoral', models.BooleanField(default=False, help_text=b'(yes)', verbose_name=b'Are you trying to win an election or referendum?')),
                ('election_date', models.DateField(blank=True, help_text=b'yyyy-mm-dd', null=True)),
                ('district', models.PositiveSmallIntegerField(blank=True, help_text=b'Leave blank for state-wide and federal elections.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignsToVoters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_contacted', models.DateField(default=None, null=True)),
                ('last_served', models.DateField(default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('level', models.CharField(choices=[(b'F', b'Federal'), (b'S', b'State, province, or territory'), (b'O', b'Other')], max_length=1)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
