"""
(C) David J. Kalbfleisch 2013

All rights reserved.  You are welcome to inspect this code for your education or to evaluate
the author's qualifications.  No other uses are permitted.
"""

# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 18:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0001_initial'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignstovoters',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voter.Voter'),
        ),
        migrations.AddField(
            model_name='campaignstovoters',
            name='voter_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voter.VoterList'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='blacklist',
            field=models.ManyToManyField(editable=False, related_name='blacklisted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='office',
            field=models.ForeignKey(blank=True, help_text=b'Leave blank for "other."', null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.Office'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='campaign', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='party',
            field=models.ForeignKey(blank=True, help_text=b'Leave blank for independent campaigns.', null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.PoliticalParty'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='prospects',
            field=models.ManyToManyField(editable=False, related_name='prospect_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='voters',
            field=models.ManyToManyField(editable=False, through='campaign.CampaignsToVoters', to='voter.Voter'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='workers',
            field=models.ManyToManyField(editable=False, related_name='works_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
