"""
(C) David J. Kalbfleisch 2013

All rights reserved.  You are welcome to inspect this code for your education or to evaluate
the author's qualifications.  No other uses are permitted.
"""

# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 18:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import voter.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0001_initial'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(blank=True, default=b'', max_length=2)),
                ('issue', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text=b'Include middle name or initial', max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dob', models.DateField(blank=True, help_text=b'yyyy-mm-dd', null=True, verbose_name=b'Date of birth')),
                ('gender', models.CharField(blank=True, choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('registration_date', models.DateField(blank=True, help_text=b'When did this person register to vote?', null=True)),
                ('registrar_id', models.CharField(blank=True, default=b'', help_text=b'Unique Id assigned by the voter registration authority', max_length=100)),
                ('dump_date', models.DateField(help_text=b'When did the registering authority dump this voter data?')),
                ('phone_number1', models.CharField(blank=True, max_length=12)),
                ('phone_number2', models.CharField(blank=True, max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name=b'e-mail')),
                ('wrong_address', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('wrong_phone_number1', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('wrong_phone_number2', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
                ('affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.PoliticalParty')),
            ],
        ),
        migrations.CreateModel(
            name='VoterContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_datetime', models.DateTimeField(auto_now_add=True)),
                ('intelligence_report', models.TextField(blank=True, default=b'""', max_length=1000)),
                ('campaigns', models.ManyToManyField(editable=False, to='campaign.Campaign')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voter.ContactMethod')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voter', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='voter.Voter')),
            ],
        ),
        migrations.CreateModel(
            name='VoterList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dump_date', models.DateField(help_text=b'yyyy-mm-dd', verbose_name=b'When did the voter registration authority give you this data?')),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Contact voters in this list?')),
                ('file_name', models.FileField(upload_to=voter.models.getUploadPath)),
                ('processed', models.CharField(default=b'No', editable=False, max_length=100)),
                ('campaign', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
            ],
        ),
    ]
